### ISSUE TITLE
Support oEmbed?

### ISSUE THREAD

**Issue by gampleman** [dmy/elm.dmy.fr#2]
Having the proper tags for that could be nice, especially for linking packages in the Elm discourse.

**Comment by rlefevre** [comment]
Yes, but shouldn't this be done in the backend? 

[elm.dmy.fr](https://elm.dmy.fr) is just a frontend alternative using the official packages.elm-lang.org backend and I doubt that oEmbed scrapers will run the javascript to get the tags.

**Comment by rlefevre** [comment]
Closing as this cannot be done from the frontend as far as I can tell.
