### ISSUE TITLE
While navigating the page, I was redirected to the original version of the Elm packages.

### ISSUE THREAD

**Issue by pogiaron** [dmy/elm.dmy.fr#3]
I navigate to this link:
https://dark.elm.dmy.fr/packages/lue-bird/elm-rosetree-path/latest/
On that page, there is a link that points to another Elm package:
https://package.elm-lang.org/packages/zwilias/elm-rosetree/latest/
Therefore, I was redirected to the light version.

**Comment by rlefevre** [comment]
This is an absolute hard coded link inside this package documentation:
https://raw.githubusercontent.com/lue-bird/elm-rosetree-path/2.0.4/README.md

Since https://dark.elm.dmy.fr can't modify the content of packages documentation, there's not much we can do to improve this inconsistency.

**Comment by pogiaron** [comment]
Ah Ok, I understand thank you.
