### ISSUE TITLE
suggestion: allow access to resources like docs.json from cross-origin requests

### ISSUE THREAD

**Issue by lue-bird** [dmy/elm.dmy.fr#4]
> I'm a total beginner to http requests, haskell servers etc so this suggestion might be unreasonable (server costs, implementation, ...).

It can be useful for websites to request and display package information.
For example, [my elm-project-metadata-diff website](https://github.com/lue-bird/elm-project-metadata-diff) needs the `docs.json` of published packages.
When a website like that directly requests this data (from elm.dmy.fr or package.elm-lang.org), it fails with a console error about the server missing the header `Access-Control-Allow-Origin`.

Adding this header to http responses with something like
```hs
applyCors snap (corsAllowOrigin Everywhere)
```
  - https://hackage.haskell.org/package/snap-core-1.0.5.1/docs/Snap-Util-CORS.html#g:1

somewhere in [here](https://github.com/dmy/elm.dmy.fr/blob/master/src/backend/Main.hs#L92) should make the resources available for cross-site sharing.

**Comment by rlefevre** [comment]
I don't have objections but elm.dmy.fr does not run a backend, it's just a proxy that replaces only the frontend (serves different HTML/Javascript files), therefore the proposed modification would only work if done on package.elm-lang.org.

That said as a proxy elm.dmy.fr can override headers so the `Access-Control-Allow-Origin: *`has been added in the web configuration (not in the haskell backend source code). Please confirm if this works.

Also note that as this goes against the actual backend which does not currently allow cross origin requests, I will remove the header if this happens to cause any issue to the actual package.elm-lang.org backend in the future.

**Comment by lue-bird** [comment]
Thank you, it works!
